### ISSUE TITLE
README out of date

### ISSUE THREAD

**Issue by ctarwater** [chef/chef-zero#123]
Minor issue, but the readme doesn't list some of the newer options (like daemon mode, ssl, generate-keys) and doesn't offer any documentation on using the features.

I'm curious, does chef-zero now provide the option of authentication? Issues 85/88 seemed to work towards that but I'm still not clear on it.

Thanks.

**Comment by JoeReid-Korrelate** [comment]
+1 to update the documentation, if possible.
