### ISSUE TITLE
`knife environment/role list` list no results unless at least one client json

### ISSUE THREAD

**Issue by patcon** [chef/chef-zero#141]
This applies for knife-zero running with local_mode = true. Haven't yet had time to minimize this down to the smallest reproducible setup, but if it's simple to reproduce, then it'll be as easy as deleting all your client keys in a chef-repo running local_mode, and running a command. Even a dummy client file works:

```
(master ✔) ᐅ cat clients/dummy.json 
{
  "name": "dummy",
  "public_key": ""
}
```

**Comment by thommay** [comment]
I can't reproduce this with current versions of chef-zero, using `knife-serve`. If you still see this, please feel free to reopen this issue.
Thanks, and apologies for the long delay in looking at this.
