### ISSUE TITLE
Question/issue - Chef Zero "caching" cookbooks

### ISSUE THREAD

**Issue by eric-tucker** [chef/chef-zero#142]
Why is it that Chef Zero caches cookbooks into the local Chef cache?  With Chef Zero (and solo?) your cookbooks already exist on the file system so is this just a side effect of running Chef server code to cache the files locally?  This seems like a needless step with Chef Zero and basically just duplicates the cookbooks on the local file system.

**Comment by glenjamin** [comment]
This is causing is some major problems when using chef zero with vagrant - the provision times are through the roof!

See https://github.com/mitchellh/vagrant/issues/5972 and https://github.com/mitchellh/vagrant/issues/6208 for more info.

**Comment by joelhandwell** [comment]
@sethvargo  should this be considered as major problem? Or vagrant officially recommends chef-solo over chef-zero for speed? But switching back to chef-solo seems temporary and not-fundamental solution as  @juliandunn said "[Although we have no immediate plans to deprecate Chef Solo, we will eventually remove it from Chef.](https://www.chef.io/blog/2014/06/24/from-solo-to-zero-migrating-to-chef-client-local-mode/)"

**Comment by eric-tucker** [comment]
This is a major issue given that I just had a server take 7 minutes just to do all of the "Storing updated ... in the cache."

That is insane and a complete waste of time.

**Comment by eric-tucker** [comment]
I tried to work-around this issue by rsyncing my zero/cookbooks folder to /etc/chef/local-mode-cache/cookbooks but Chef doesn't seem to like this as it's storing a manifest somewhere of the cookbooks.

Can you please provide a work-around that would allow me to reduce the time zero needs to get going?

**Comment by andreamaruccia** [comment]
+1 wastes a lot of time indeed. anyone has found a workaround yet?

**Comment by eric-tucker** [comment]
This may have been resolved in Chef 12.5.1 via another issue but I can't seem to locate it.

**Comment by iiro** [comment]
I started using 12.5.1 when it was out and it fixed this problem. Works like a charm.

**Comment by andreamaruccia** [comment]
yes it seems that it's correct thx for letting me know!
