### ISSUE TITLE
files directory missing in /var/chef/cache/cookbooks/cookbook_name after chef-client run

### ISSUE THREAD

**Issue by poliva83** [chef/chef-zero#149]
Can someone clarify if this is expected or not? I am using chef provisioning to converge a node and its pointed at a chef zero server. I developed cookbook_name below with "files/default/" that has 3 small gem files.

```
poliva@poliva-chef-provisioning-ws:~/cookbook_name$ ls
attributes  Berksfile  Berksfile.lock  CHANGELOG.md  chefignore  files  Gemfile  metadata.rb  README.md  recipes  Thorfile  Vagrantfile
```
I uploaded cookbook to chef zero server. `knife cookbook show cookbook_name 0.1.0` shows files exist under "files/default/".

```
poliva@poliva-chef-provisioning-ws:~/cookbook_name$ knife cookbook show cookbook_name 0.1.0 files
checksum:    24c0bb0abdbf098ad116c1bb5a6a1905
name:        open4-1.3.4.gem
path:        files/default/open4-1.3.4.gem
specificity: default
url:         http://localhost:7799/file_store/checksums/24c0bb0abdbf098ad116c1bb5a6a1905

checksum:    1a95892a53a34080d56abce8b5714e52
name:        di-ruby-lvm-0.1.3.gem
path:        files/default/di-ruby-lvm-0.1.3.gem
specificity: default
url:         http://localhost:7799/file_store/checksums/1a95892a53a34080d56abce8b5714e52

checksum:    d79264664ab78e943e18c2f203fa5c21
name:        di-ruby-lvm-attrib-0.0.14.gem
path:        files/default/di-ruby-lvm-attrib-0.0.14.gem
specificity: default
url:         http://localhost:7799/file_store/checksums/d79264664ab78e943e18c2f203fa5c21
```

When node comes up it downloads cookbook during chef-client run converges as normal.

```
                                 Starting Chef Client, version 11.18.6
                                 resolving cookbooks for run list: ["cookbook_name::default"]
                                 Synchronizing Cookbooks:
                                   - cookbook_name
                                   - apt
                                   - lvm
                                 Compiling Cookbooks...

```

However the files directory is missing when I check the cached copy that was downloaded to the node.

```
local@poliva-node:/var/chef/cache/cookbooks/cookbook_name$ ls
attributes  Berksfile  Berksfile.lock  chefignore  Gemfile  metadata.json  README.md  recipes  Thorfile
```

Confused why this is happening since `knife cookbook download cookbook_name 0.1.0` downloads copy fine locally on my provisioning workstation with files directory included.

**Comment by poliva83** [comment]
When I add a plain text banner into files directory and use it with a cookbook_file resource the files directory shows up in `/var/chef/cache/cookbooks/cookbook_name`. However the gem files still did not show up. Wondering if it possibly has something to do with format (gem file vs plain text).

**Comment by thommay** [comment]
Hi,
sorry for the slow response. This is as expected - in Chef 11 files are lazy loaded by the client based on usage in a recipe. In Chef 12, files are automatically loaded at the start of the run.
What's the use case that you are/were attempting here - trying to use the gem without necessarily needing it to be installed? 
Again, sorry for the slow response.
-Thom

**Comment by poliva83** [comment]
@thommay Unfortunately I forgot what the use case was for this now. Pretty sure I worked around the issue and was just reporting because it seemed confusing. I have since moved on from chef 11 client anyway.
