### ISSUE TITLE
Implement missing Chef 12 endpoints

### ISSUE THREAD

**Issue by andrewjamesbrown** [chef/chef-zero#153]
The following CS12 endpoints are currently unimplemented in Chef Zero, which makes the build fail.  Currently it is worked around by explicitly disabling them, which should be enabled once the endpoints are working.

```
'--skip-policies',
'--skip-server-api-version',
'--skip-cookbook-artifacts',
'--skip-containers',
'--skip-api-v1'
```

**Comment by marcparadise** [comment]
I'm going to split --skip-api-vi into its own thing, since there's a fair bit of work there - we'll  need support API versioning as a whole, since that's how we're introducing modified functionality into the API.

**Comment by tyler-ball** [comment]
api-v1 - https://github.com/chef/chef-zero/issues/154

**Comment by andrewjamesbrown** [comment]
I've fixed --skip-server-api-version in https://github.com/chef/chef-zero/pull/155, which also has the beginnings of fixes for https://github.com/chef/chef-zero/issues/154

**Comment by andrewjamesbrown** [comment]
It looks like @danielsdeleo fixed cookbook-artifacts in https://github.com/chef/chef-zero/pull/112 but that PR will need to be rebased and tests passing.

**Comment by thommay** [comment]
the only missing chef 12 endpoint now is `/universe`.
