### ISSUE TITLE
API Versioning Support

### ISSUE THREAD

**Issue by marcparadise** [chef/chef-zero#154]
In order to achieve feature parity with Chef Server 12.1 and later, API versioning support will need to be introduced.  

For reference, here is what will need to be implemented: 
- https://github.com/chef/chef-server/blob/master/omnibus/RELEASE_NOTES.md#deprecations
- https://github.com/chef/chef-server/blob/master/omnibus/RELEASE_NOTES.md#changes-in-behavior
- https://github.com/chef/chef-server/blob/master/omnibus/RELEASE_NOTES.md#api-changes-and-additions "Changed Implemented under API v1+"

If you run 'make' in this directory it will generate the docs that detail the API v1 changes to client and user endpoints: 
https://github.com/chef/chef-server/tree/master/src/oc_erchef/raml-docs

And here's the RFC which overall specifies how the API version header behaviors work: 

https://github.com/chef/chef-rfc/blob/master/rfc041-server-api-versioning.md

**Comment by andrewjamesbrown** [comment]
@marcparadise, what are your thoughts on how to go about specifying the minimum and maximum supported API versions in Chef Zero?  Global variables, configuration parameters, other?  I've started a skeleton implementation for this issue as well as https://github.com/chef/chef-zero/issues/153, but using magic numbers to specify min/max seems very wrong.
