### ISSUE TITLE
Support yaml objects in addition to json

### ISSUE THREAD

**Issue by patcon** [chef/chef-zero#156]
I kinda miss the ruby DSL, but one of the main reasons is because it allowed me to be more semantic and explanatory in the node/role/environment files. Any chance we could support yaml files, which would at least allow inline comments?

**Comment by patcon** [comment]
For context, I'm using `knife-zero` (ie. local_mode enabled).

**Comment by thommay** [comment]
We've got ruby support now, and I'm reluctant to add any further formats. But if you wanted to pull a PR together we could at least discuss it.
