### ISSUE TITLE
Nested library files aren't supported with file_store

### ISSUE THREAD

**Issue by daften** [chef/chef-zero#161]
Hi,

I got this issue when trying to move from knife-solo (with chef-solo-search) to knife zero. The relevant issue can be found here: https://github.com/higanworks/knife-zero/issues/53

However, this seems to be a bug in chef-zero that might cause problems for other cookbooks as well.

To reproduce: chef-repo with all the relevant configuration and chef-solo-search as a cookbook in the repo. Then start up the server with knife serve:
```
$ curl http://127.0.0.1:8889/file_store/repo/cookbooks/chef-solo-search/libraries/search.rb
#=> found

$ curl http://127.0.0.1:8889/file_store/repo/cookbooks/chef-solo-search/libraries/search/parser.rb
#=> not found
```

**Comment by sawanoboly** [comment]
:+1:

**Comment by tcdowney** [comment]
Is this related to these issues?
* https://github.com/test-kitchen/test-kitchen/issues/59
* https://github.com/chef/chef-zero/issues/118

Specifically this comment from @kplimack:
> @jtimberman, I'm still grok'ing through the CZ code, but could this be it?
https://github.com/chef/chef-zero/blob/ea00a7786143fd32f6b1e937ce768100ff0beece/lib/chef_zero/chef_data/cookbook_data.rb#L142

Either way, I'm getting 404s from Chef Zero for nested library files during test kitchen runs, so :+1:.

**Comment by marbe** [comment]
Hi,
we were struggling with the very same problem on a custom company cookbook, when we found this issue.
Adding my 2 cents, I tested that *the issue is present since chef-12.0.0*.
The only chef version that is *free from this issue* is the first-one to have chef-zero with local mode included: *chef-11.12.8-2*
Hope this info can be helpful :-)
Is anyone having a look at it?

**Comment by szymonpk** [comment]
Is there any reason for [disabling recursive libraries](https://github.com/chef/chef-zero/blob/master/lib/chef_zero/chef_data/cookbook_data.rb#L147) load in chef-zero? Because this is still 'a thing' and chef-zero behaviour differs from normal chef server.

**Comment by joegoggins** [comment]
Great question @szymonpk (and link), the technical change to make this work is literally about swapping that 3rd argument from `false` to `true`. There must be a reason that we're unaware for intentionally loading libraries recursively. I'm Happy to issue a PR to make this change myself if I know it's something maintainers are into, let me know.

**Comment by szymonpk** [comment]
Originally this code was introduced by @jkeiser. Maybe he will throw a little bit more light on it. Or maybe you can go with PR and we'll see what'll break ;-)

**Comment by szymonpk** [comment]
@thommay in which release? I see only 4.7.1 from 7th.

**Comment by thommay** [comment]
Apologies, looks like we only fixed that in chef, not chef-zero.
