### ISSUE TITLE
Pruned output when searching with environment filter in local_mode

### ISSUE THREAD

**Issue by patcon** [chef/chef-zero#168]
When an environment filter is applied either in knife.rb or with the CLI arg, the output of the search results are pruned to show just the `chef_environment`:

```rb
# .chef/knife.rb
local_mode true
```

```
~/blendive/chef-repos/blendive-chef-repo (master ✘)✹✭ ᐅ knife search node "recipes:elkstack\:\:default" --environment production 
2 items found

chef_environment: testing

chef_environment: production

~/blendive/chef-repos/blendive-chef-repo (master ✘)✹✭ ᐅ knife search node "recipes:elkstack\:\:default"                         
2 items found

<PROPER EXTENDED OUTPUT THAT RESPONDS TO `--long` and `--medium` flag>
```

Add the `--id-only` flag or an `--attribute <some attr>` arg allows more to be shown, but there doesn't seem to be any other way to get it showing more full output.

Should I dig into chef-zero, or does this sound like a knife problem?

**Comment by patcon** [comment]
fwiw, `--format json` shows only the "chef_environment" key

**Comment by thommay** [comment]
This looks like a knife problem, since I can reproduce it against hosted chef. Please can you file a bug against chef?
