### ISSUE TITLE
kitchen and chef-zero 404ing on data bag

### ISSUE THREAD

**Issue by gopearls42** [chef/chef-zero#198]
Hi,

I think I've read previous issues with the same problem but I still cannot get data bags working with test-kichen. I get:

```
[2016-02-06T18:53:23+00:00] ERROR: Failed to load data bag item: "rabbit" "client"
Net::HTTPServerException
       ------------------------
       404 "Not Found"
```

My data bag is ..

```
$ ls test/data_bags
rabbit.json

$ cat test/data_bags/rabbit.json 
{ 
    "id": "rabbit",
    "client": "foo"
}
```

The specification for kitchen is ...

```
$ cat .kitchen.yml
...
provisioner:
  name: chef_zero
...
suites:
  - name: monitor
    run_list: [ "recipe[my_it::monitor]" ]
    data_bags_path: test/data_bags
    provisioner:
      client_rb:
        environment: dev
```

**Comment by engel75** [comment]
could you please run

`kitchen diagnose monitor`

**Comment by thommay** [comment]
sorry to read this so late, but that's not the correct way to create a data bag.
Have a look at http://atomic-penguin.github.io/blog/2013/06/07/HOWTO-test-kitchen-and-encrypted-data-bags/ , but you should have a directory structure `test/data_bags/rabbit` with a file `client.json`.

**Comment by amoonakal** [comment]
test

**Comment by amoonakal** [comment]
What should be the approach to use kitchen to test policies which have databag references. Any help....
