### ISSUE TITLE
chef-zero should make data available on save

### ISSUE THREAD

**Issue by swettk** [chef/chef-zero#209]
It would be helpful if when attribute and databags data is stored it was immediately available.  

node.save
databag_item.save

We're having to run converges twice with attribute changes to accommodate the creation, then use of this info.

**Comment by thommay** [comment]
Hi,
how are you running chef-zero? Updates should be immediately available. Can you describe the sequence of things that you're doing?
Thanks

**Comment by swettk** [comment]
we're running zero as part of a Vagrant run (vagrant up)

**Comment by thommay** [comment]
OK, I need much more information - please can you provide a sample recipe demonstrating the problem, and a vagrant config too?

**Comment by lamont-granquist** [comment]
this would need a better repro case, like a github repo with simple repro instructions after cloning it.
