### ISSUE TITLE
Chef zero outputs too much information for info log level

### ISSUE THREAD

**Issue by maxlazio** [chef/chef-zero#215]
Hi all,

I have a question about a change introduced with https://github.com/chef/chef-zero/pull/199 . During some refactoring there the verbosity of the chef-zero run changed, [like in this line](https://github.com/chef/chef-zero/pull/199/files#diff-ff6a25f20f74077c95639406ddbcdfe1R42). 
This will show quite a lot of information like:

```
[2016-04-21T10:21:49+00:00] INFO: GET /organizations/chef/nodes/organization
[2016-04-21T10:21:49+00:00] INFO: #<ChefZero::RestErrorResponse: 404: Object not found: chefzero://localhost:8889/nodes/hostname>
```

and quite a lot of `"--- END RESPONSE ---"` `"---  PUT BODY ---"` and so on.

I am curious if this was done on purpose or was it an oversight? Since I am using `chef-client -z` with `client.rb` configuration file, I don't suppose there is an easy way to specify a different log level for chef-zero?

**Comment by stevendanna** [comment]
I've moved what I see as one of the worse offenders of excess logging to the debug log level:

https://github.com/chef/chef-zero/pull/216

But I would be 👍 on something that allows us to have better control over the chef-zero log level when running `chef-client -z`

**Comment by maxlazio** [comment]
Thanks for the quickfix @stevendanna! 

When the time permits, will take a look at what can be done with log level of chef-zero when using `chef-client -z`.

**Comment by stanhu** [comment]
Can we also demote [this line](https://github.com/chef/chef-zero/blob/7bc90e7eb7ca0d58df1785ffae2a33177634c1fe/lib/chef_zero/rest_router.rb#L42) to debug?
