### ISSUE TITLE
Should do a release

### ISSUE THREAD

**Issue by coderanger** [chef/chef-zero#234]
4.8.0 is busted on everything because of that quotes issue. Should ship a 4.8.1 ASAP to unbreak there :)

**Comment by theckman** [comment]
It seems that e257f450c044616fefbd15e9a180387aaaa572a1 accidentally fixed a bug in `bin/chef-zero`. It's a syntax error so it impacts all platforms.

**Comment by theckman** [comment]
Here is the specific line: https://github.com/chef/chef-zero/commit/e257f450c044616fefbd15e9a180387aaaa572a1#diff-a2a4711aebb6fc27c21c8481c60db638R103

**Comment by thommay** [comment]
nothing accidental about it, but yes, we should do a new release.

**Comment by theckman** [comment]
@thommay I only mention accidental because the commit for e257f45 doesn't mention that a bug fix is included. Makes it seem like it's only style.

**Comment by thommay** [comment]
yeah, the fix itself was in https://github.com/chef/chef-zero/commit/1e9200bd055a0c15836adf0c6c75a8c20ad77887

**Comment by theckman** [comment]
Ah, seen. I misread the diff when I looked at it originally. Cheers!

**Comment by thommay** [comment]
I did a release.
