### ISSUE TITLE
Improper require of Hashie causing error (NameError: uninitialized constant Hashie::Extensions::Array)

### ISSUE THREAD

**Issue by alecxvs** [chef/chef-zero#244]
See: https://github.com/intridea/hashie/issues/367

Hashie is being required (`require "hashie/mash"`) [here](https://github.com/chef/chef-zero/blob/master/lib/chef_zero/chef_data/cookbook_data.rb#L2), but according to the above issue, it should also `require "hashie"` prior to that. The version of hashie is not restricted, so a bundle or gem update will cause this issue when using chef-zero (in my case, specifically, using Chefspec).

~~I suspect Hashie 3.4.5 will be fixed or reverted, but~~ compatibility with newer versions will likely depend on fixing this.

**Comment by dblock** [comment]
I released hashie 3.4.6 so this shouldn't be necessary, but for making things future-proof I recommend changing this to a `require 'hashie'`.

**Comment by lamont-granquist** [comment]
tactically we should fix this.

strategically we should probably replace hashie with Chef::Mash to reduce external deps if possible.

**Comment by jeremydyoung** [comment]
I think this has cropped up again with Hashie 3.5.0:

https://github.com/intridea/hashie/issues/391

**Comment by dblock** [comment]
Yes, sigh. I'm working on a way to have a spec for this.

**Comment by jeremydyoung** [comment]
Resolved again by Hashie 3.5.1

Tested to verify.
