### ISSUE TITLE
Completely arbitrary ruby version requirement

### ISSUE THREAD

**Issue by rabidscorpio** [chef/chef-zero#268]
In commit https://github.com/chef/chef-zero/commit/1f3952ee148606f01e0b1680e6e6e42bf1b5c7b7 the minimum ruby version was changed from ```2.2.2``` to ```2.3.1```. There's no explanation anywhere as to why this was done and appears to be completely arbitrary (although I get that this is the version in chefdk). Can this please be reverted? It's a totally unnecessary bump. Thanks!

**Comment by lamont-granquist** [comment]
no.  we drop support for old rubies as they fall into security-only mode, which matches what the ruby community does.

**Comment by rabidscorpio** [comment]
That's ridiculous, this isn't ruby, this is chef and I don't need the latest ruby release to run chef-zero.
