### ISSUE TITLE
Searches for node `role:SOMESTRING` are returning nested attributes

### ISSUE THREAD

**Issue by bmhatfield** [chef/chef-zero#54]
I have an HAProxy cookbook that allows us to set up backends in an automated fashion. To do this, we specify a hash of roles that should be searched for, and automatically added to the load balancer on some port:

```
default[:haproxy][:backends] = [
  { :role => 'SOMEROLE', :port => '3250' },
  { :role => 'settings', :port => '80' }
]
```

However, SOMEROLE doesn't exist yet. At all. It's not mapped to any node, it doesn't exist on chef-zero, we haven't created it. We expect search to return no results for a search for it.

Searching the expanded runlist behaves as expected:

```
$ knife search node "roles:SOMEROLE"
0 items found
```

But searching for the non-expanded runlist (which happens to have a key collision with 'role' that's deep in a nested attribute) returns bad results:

```
$ knife search node "role:SOMEROLE"
1 items found

Node Name:  vagrant-ubuntu-precise
Environment: local
FQDN:        vagrant-ubuntu-precise
IP:          10.0.2.15
Run List:    role[base], role[haproxy-mid-tier]
Roles:      base, haproxy-mid-tier
Recipes:    [..snip..]
Platform:    ubuntu 12.04
Tags:
```

Clearly, this is bad. http://docs.opscode.com/essentials_search.html#nested-fields says that nested attributes are expanded to the top level (which is kind of a crazy idea, but I digress) but http://docs.opscode.com/essentials_search.html#roles-in-run-lists specifically says that `role:` and `roles:` have special behavior.

**Comment by martinb3** [comment]
I'm seeing the same symptom with tags and search. When I save a nested key `tags`, e.g. `node.set['foo']['bar']['tags']='foo'`, searching for a tag `foo` returns that node, even though it is clearly not tagged with `foo`.
