### ISSUE TITLE
Attribute and Template Overrides

### ISSUE THREAD

**Issue by jweiss** [chef/chef-zero#62]
I'm not sure if this is a chef-zero issue or in general how chef-server behaves.

I'm currently using chef-solo 11.10. There I can override templates that are used in recipes from the cookbooks directory by supplying them in site-cookbooks in the same path, e.g. 

```text
cookbooks/apache2/templates/default/apache.conf.erb
site-cookbooks/apache2/templates/default/apache.conf.erb
```

When I run chef-client in local mode against chef-zero, my template override is ignored and only the original in 'cookbooks' is loaded. The same applies to attribute files.

As it works in chef-solo I'm not sure if this is how it is supposed to work or a bug in my client.rb or even chef-zero?

Thanks!

**Comment by thommay** [comment]
Given that there's now a supported API to modify resources such that one can point to different template files and so on, and we still don't want to support merging, I'm going to close this issue.
Thanks,
-Thom
